### ISSUE TITLE
Can SDK be used without any hardware from Wirepas?

### ISSUE THREAD

**Issue by shiphananadi** [wirepas/wm-sdk#26]
Hi,
I have a confusion regarding the following statement:
" This repository contains Wirepas SDK, which allows the development of an application to be executed on the same chip as Wirepas Stack. This application is often referred to as a Single-MCU application." 
To use the SDK, is it mandatory to get hardware from Wirepas? Or can we also use it on some other hardware (in my case Nordic MCU) to create our own applications?
Thanks in advance.

**Comment by GwendalRaoul** [comment]
Hello,
Wirepas is not making any hardware and Wirepas can run on Nordic MCU.
But to use the SDK, you need to have access to the Wirepas binaries. You need to have a software license agreement (SLA) with Wirepas to get them. If you would like to become a SLA licensee, please contact sales@wirepas.com
Best regards,
Gwendal
